version: '3.3'

services:
  spring-jwt:
    build: .
    image: salesmgmt-authorization:v1
    container_name: salesmgmt-authorization
    command: java -jar /salesmgmt-authorization.war
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 250m
        reservations:
          memory: 200m