server:
  port: 8080

spring:
  application:
    name: salesmgmt

salesmgmt:
  authentication:
    url: https://spring-security-jwt-module.herokuapp.com/api/auth/authorize
  swagger:
    base-package: org.personal.salesmgmt
    base-path: "/api.*"

