spring:
  application:
    name: salesmgmt

  profiles:
    active: @spring.profiles.active@

salesmgmt:
  authentication:
    url: https://spring-authentication-module.herokuapp.com/api/auth/authorize
  swagger:
    base-package: org.personal.salesmgmt
    base-path: "/api.*"
  client:
    client-urls: https://gentle-inlet-72611.herokuapp.com/

